name: "Test Action"

on:
  push:
    branches:
      - "**"

env:
  source: "${{ format('{0}-{1}-{2}', 'tests-source', github.run_id, github.run_number) }}"
  destination: "${{ format('{0}-{1}-{2}', 'tests-destination', github.run_id, github.run_number) }}"
  example-file: "example-change.test"

jobs:
  fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: "git checkout -b ${{ env.destination }}"
      - run: "git checkout -b ${{ env.source }}"
      - run: "echo ${{ env.destination }} > ${{ env.example-file }}"
      - run: "git add example-change.test"
      - run: "git commit -m 'chore: Add example file'"
      - run: "git push --set-upstream origin ${{ env.destination }} ${{ env.source }}"
  merge:
    runs-on: ubuntu-latest
    needs:
      - fixtures
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ env.destination }}"
          fetch-depth: 0
      - uses: ./
        with:
          from: "origin/${{ env.source }}"
  assert:
    runs-on: ubuntu-latest
    needs:
      - merge
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "${{ env.destination }}"
      - id: example-file
        run: "echo ::set-output name=body::$(cat ${{ env.example-file }})"
      - uses: pr-mpt/actions-assert@v2
        with:
          assertion: npm://@assertions/is-equal
          expected: "${{ env.destination }}"
          actual: "${{ steps.example-file.outputs.body }}"
  clean-up:
    runs-on: ubuntu-latest
    needs:
      - assert
    steps:
      - name: Delete test branches
        run: git push origin --delete ${{ env.source }} ${{ env.destination }}
